name: my_vessels
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  flutter_layout_grid: 1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: 4.0.0
  flutter_riverpod: 2.0.0-dev.5
  go_router: 3.0.3
  intl: 0.17.0
  rxdart: 0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/vessels/
